version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge-net

    
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    volumes:
      - ./node:/usr/src/app:rw
      - /usr/src/app/node_modules
      
    networks:
      - challenge-net
    tty: true
    depends_on:
      - db
      

  nginx:
    container_name: proxy
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - challenge-net  
    depends_on:
      - app    


networks:
  challenge-net:
    driver: bridge